### Einops tutorial

In [1]:
import numpy

In [5]:
ims = numpy.load("../test_images.npy", allow_pickle=False)

In [6]:
ims.shape,ims.dtype

((6, 96, 96, 3), dtype('float64'))

In [7]:
ims[0]

array([[[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        ...,
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078]],

       [[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        ...,
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078]],

       [[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        ...,
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078]],

       ...,

       [[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0

In [3]:
import math
import torch
import torch.nn.functional as F
import torch.nn as nn
from einops import rearrange, einsum, reduce

In [13]:
x = torch.ones(2, 2, 3) # batch seq hidden
y = torch.ones(2, 2, 3) # batch seq hidden

2 * 3 @ 3 * 2

In [14]:
z = x @ y.transpose(-2,-1)

In [15]:
z

tensor([[[3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.]]])

In [16]:
x1 = torch.ones(3, 4) # seq1 hidden
y1 = torch.ones(4, 3) # hidden seq2

In [17]:
z1 = x1 @ y1

In [18]:
z1

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [21]:
zz1 = einsum(x1, y1, "seq1 hidden, hidden seq2 -> seq1 seq2")

In [22]:
zz1

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [24]:
xx = torch.ones(2, 3, 4) # batch seq1 hidden
yy = torch.ones(2, 3, 4) # batch seq2 hidden

In [27]:
xx

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [30]:
zz = xx @ yy.transpose(-2, -1)

In [31]:
zz

tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])

In [28]:
zz = einsum(xx,yy,"... seq1 hidden, ... seq2 hidden -> ... seq1 seq2")

In [29]:
zz

tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])

In [33]:
xx

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [34]:
yy1 = xx.sum(dim=-1)

In [36]:
yy1.shape

torch.Size([2, 3])

In [41]:
x

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [42]:
yy1 = reduce(x, "... hidden -> ...", "sum")

In [43]:
yy1

tensor([[3., 3.],
        [3., 3.]])

In [46]:
x_w = torch.ones(3,8) # seq total_hidden

w = torch.ones(4,4) # hidden1 hidden2

In [49]:
x_w

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [47]:
x_w = rearrange(x_w, "... (heads hidden1) -> ... heads hidden1", heads=2)

In [48]:
x_w

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [53]:
x_w.shape

torch.Size([3, 2, 4])

In [52]:
w

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
x_w = einsum(x_w,w,"... hidden1, hidden1 hidden2 -> ... hidden2")

In [51]:
x_w

tensor([[[4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.]]])

In [54]:
x_w.shape

torch.Size([3, 2, 4])

In [55]:
x_w = rearrange(x_w, "... heads hidden2 -> ... (heads hidden2)")

In [56]:
x_w

tensor([[4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.]])

In [57]:
x_w.shape

torch.Size([3, 8])